### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by shaharsu** [holehouse-lab/shephard#2]
https://github.com/holehouse-lab/shephard/blob/e484f11a49a5797526c868bc516be39e91c4581d/docs/getting_started.rst

si_domains.add_domains_from_file(proteome, 'domains_file.tsv')
should be
si_domains.add_domains_from_file(P, 'domains_file.tsv')

**Comment by alexholehouse** [comment]
Thanks bud!  These issues have been fixed in the most recent commit.
